### PR TITLE
Updates tinacms @ 0.66.5 and adds RouteMapperPlugin

### PR DESCRIPTION
**Pull request by Enigmatical**

### CODE REVIEW

**Comment by logan-anderson** [comment]
Can we remove the feature flag as well?

**Comment by logan-anderson** [comment]
Should we remove the slug field?

**Review by logan-anderson — APPROVED** [review]
Looks good to me! I don't think you _need_ to address my comment. it can be fixed in another PR

**Comment by Enigmatical** [comment]
> Should we remove the slug field?
> 
> For context if I have a file named `test.md`. This will cause an error Screen Shot 2022-02-24 at 3 40 00 PM
> 
> because we are looking at /docs/filename?

Agreed and done.

**Review by logan-anderson — APPROVED** [review]

**Pull request merged**
